### ISSUE TITLE
Could not load library cudnn_ops_infer64_8.dll. Error code 126

### ISSUE THREAD

**Issue by Jason-K** [markgoodhead/dictate-wizard#2]
Could not load library cudnn_ops_infer64_8.dll. Error code 126
Please make sure cudnn_ops_infer64_8.dll is in your library path!

**Comment by markgoodhead** [comment]
@Jason-K Please try again now on master, I think I've resolved this now

**Comment by Jason-K** [comment]
@markgoodhead Fixed. Thanks, Mark! I'm just starting to futz with Whisper in an effort to get rid of Dragon. There's just not a ton of activity for Windows users, so thanks for helping us all out!
